language: node_js
node_js:
  - 4.2.2
  - node
  - iojs
before_script:
  - npm install
  - npm install coveralls
after_script:
  - cat out/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
